#!/bin/bash

bluetooth | grep on >/dev/null

case $BLOCK_BUTTON in
  1) bluetooth-wizard & ;;
  3) bluetooth-sendto & ;;
esac

if [[ $? = 0 ]]; then
	echo 
	echo 
	echo \#0000FF
else
	echo
	echo
fi
